### ISSUE TITLE
Update naming conventions and config structure

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-py-telemetry#13]
Config.yaml currently contains the following: 
```yaml
catalog:
  endpoint: /intake/update
  items:
    - esm_datastore.search
    - DfFileCatalog.search
    - DfFileCatalog.__getitem__
payu: 
  endpoint: /payu/update
  items:
    - Experiment.run
```
which is of the more general form
```yaml
service_1: 
  endpoint: endpoint_1
  items:
    - s1_li_1
    - s1_li_2
service_2:
  endpoint: endpoint_2
  items:
    - s2_li_1
    - s2_li_2
service_$N
```

This structure is necessary in order to respect the structures of the `ApiHandler` and `TelemetryRegister` classes.  However, it enforces that we can only have a single endpoint per service. Conceptually, a service should really map to a Django app, and an endpoint to a model serializer, and so as things currently stand, we can only have one model per app, unless we resort to confusing tricks like 
```yaml
catalog:
  endpoint: /intake/update
  items:
    - esm_datastore.search
    - DfFileCatalog.search
    - DfFileCatalog.__getitem__
payu_run: 
  endpoint: /payu_run/update
  items:
    - Experiment.run
payu_restart: 
  endpoint: /payu_restart/update
  items:
    - Experiment.run
```

This needs fixing, so we have a schema more like
```yaml
service_1: 
  endpoints:
    - endpoint_1:
      - s1_li_1
      - s1_li_2
    - endpoint_2:
      - s1_li_1
      - s1_li_2

...
```
eg
```yaml
payu: 
  endpoints:
    - run:
      - Experiment.run
    - restart:
      - Experiment.restart
catalog:
  endpoints:
    - update:
      - esm_datastore.search
      - DfFileCatalog.search
      - DfFileCatalog.__getitem__
...
```

**Comment by charles-turner-1** [comment]
This can be further simplified by building the endpoints procedurally from the yaml structure: eg.
```yaml
catalog:
  update:
    - esm_datastore.search
    - DfFileCatalog.search
    - DfFileCatalog.__getitem__
payu:
  run:
    - Experiment.run
  restart:
    - Experiment.restart
```

where calls to `esm_datastore.search`, `DfFileCtalog.search`, or `DfFileCatalog.__getitem__` would send post requests to `/catalog/update` etc.
