### ISSUE TITLE
AST Parsing robustness

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-py-telemetry#30]
The AST listener uses `config.yaml` to listen for calls & send telemetry when the right calls are found, eg.
```yaml
intake:
  catalog:
    - esm_datastore.search
    - DfFileCatalog.search
    - DfFileCatalog.__getitem__
payu: 
  run: 
    - Experiment.run
  restart:
    - Experiment.restart
```
 `esm_datastore.search` will listen for that function call, and post telemetry to `.../intake/catalog` 

I need to double check that this doesn't depend on how things are imported - eg. will the following be caught correctly:
```diff
intake:
  catalog:
    - esm_datastore.search
    - DfFileCatalog.search
    - DfFileCatalog.__getitem__
+  builder:
+    - AccessOm2Builder.build
payu: 
  run: 
    - Experiment.run
  restart:
    - Experiment.restart
```

Questions to confirm:
1. [ ] Will inheritance break this? Eg. if `AccessOm2Builder.build` is a method defined on a parent class, is this still going to work?
2. [ ] Will we get issues depending on the import style, eg.
```python
from access_nri_intake import builders
...
builders.AccessOm2Builder.build()
```
Will this still be caught as if we had performed the following?
```python
from access_nri_intake.builders import AccessOm2Builder
...
AccessOm2Builder.build()
```
