### ISSUE TITLE
Restrict to intake catalog for intitial release

### ISSUE THREAD

**Issue by charles-turner-1** [ACCESS-NRI/access-py-telemetry#33]
Currently, the `config.yaml` is basically just a demo skeleton:
```yaml
intake:
  catalog:
    - esm_datastore.search
    - DfFileCatalog.search
    - DfFileCatalog.__getitem__
payu: 
  run: 
    - Experiment.run
  restart:
    - Experiment.restart
```

This needs cleaning up.
